export interface DailyContentPlanSummary {
  checked: true;
  mode: "preview" | "apply";
  planVersion: "9F-2A";
  planMode: "daily_auto_content_plan_draft";
  profileFound: boolean;
  profileHealthy: boolean;
  planWouldBeCreated: boolean;
  planWouldBeUpdated: boolean;
  existingPlanFound: boolean;
  existingPlanId: string | null;
  persistedPlanId: string | null;
  persistedPlanStatus: string | null;
  persistedItemCount: number;
  persistedApprovalRequiredCount: number;
  persistedContentItemLinkedCount: number;
  persistedGenerationAllowedCount: number;
  persistedPublishExecutionAllowedCount: number;
  persistedScheduledPublishAllowedCount: number;
  existingPlanSummary: {
    id: string;
    planDateLocal: string;
    status: string;
    planKind: string;
    operationMode: string;
    defaultPublishPolicyPreset: string;
    contentGenerationEnabled: boolean;
    llmCallEnabled: boolean;
    publishExecutionEnabled: boolean;
    scheduledPublishEnabled: boolean;
    plannedItemCount: number;
    persistedItemCount: number;
  } | null;
  existingPlanItems: Array<{
    id: string;
    itemOrder: number;
    slotKey: string;
    status: string;
    topicSeed: string;
    contentIntent: string;
    audienceHint: string | null;
    riskNote: string | null;
    publishMode: string;
    contentItemId: string | null;
    draftGenerationAllowed: boolean;
    llmGenerationAllowed: boolean;
    publishExecutionAllowed: boolean;
    scheduledPublishAllowed: boolean;
    requiresHumanApproval: boolean;
  }>;
  appliedPlan: {
    id: string;
    planDateLocal: string;
    status: string;
    planKind: string;
    operationMode: string;
    defaultPublishPolicyPreset: string;
    contentGenerationEnabled: boolean;
    llmCallEnabled: boolean;
    publishExecutionEnabled: boolean;
    scheduledPublishEnabled: boolean;
    plannedItemCount: number;
    persistedItemCount: number;
  } | null;
  appliedItemCount: number | null;
  applyAttempted: boolean;
  applyBlocked: boolean;
  applyOk: boolean;
  featureFlagEnabled: boolean;
  confirmationPhraseAccepted: boolean;
  targetBloggerBlogId: string;
  targetBloggerBlogName: string | null;
  targetBloggerBlogUrl: string | null;
  planDateLocal: string;
  timezone: "Asia/Seoul";
  operationMode: "approval_required";
  defaultPublishPolicyPreset: "safe_manual_publish";
  contentGenerationEnabled: false;
  llmCallEnabled: false;
  publishExecutionEnabled: false;
  scheduledPublishEnabled: false;
  policySnapshot: Record<string, unknown>;
  planItems: Array<{
    syntheticPlanItemId: string;
    itemOrder: number;
    slotKey: string;
    topicSeed: string;
    contentIntent: string;
    audienceHint: string;
    riskNote: string;
    publishMode: "approval_required";
    draftGenerationAllowed: false;
    llmGenerationAllowed: false;
    publishExecutionAllowed: false;
    scheduledPublishAllowed: false;
    requiresHumanApproval: true;
    operatorTakeaway: string;
  }>;
  planTotals: {
    plannedItemCount: number;
    approvalRequiredCount: number;
    llmGenerationAllowedCount: 0;
    publishExecutionAllowedCount: 0;
    scheduledPublishAllowedCount: 0;
  };
  guardrailSummary: {
    noContentGeneration: true;
    noLlmCall: true;
    noContentItemMutation: true;
    noBloggerWrite: true;
    noPublishExecution: true;
    noScheduledPublish: true;
    profilePolicyUsed: boolean;
  };
  blockingReasons: string[];
  warnings: string[];
  sideEffectSummary: {
    dbRead: boolean;
    dbWrite: boolean;
    schemaMigration: boolean;
    bloggerRead: false;
    bloggerWrite: false;
    bloggerPublish: false;
    bloggerUpdate: false;
    bloggerDraftSave: false;
    tokenRefresh: false;
    oauthReconnect: false;
    contentGeneration: false;
    contentMutation: false;
    approvalMutation: false;
    attemptMutation: false;
    llmCall: false;
    externalSend: false;
  };
}

export interface DailyContentPlanResponse {
  checkedAt: string;
  dailyContentPlanSummary: DailyContentPlanSummary;
}
